-------------------------------------------------------------------
-- DDL for USER_ROLE Table
-------------------------------------------------------------------
CREATE TABLE USER_ROLE (
  USER_ROLE_ID 			int(20) NOT NULL AUTO_INCREMENT,
  NAME 					varchar(100) NOT NULL,
  DESCRIPTION			varchar(255) DEFAULT NULL,
  STATUS				varchar(50) NOT NULL,
  ROLE_TYPE				varchar(50) DEFAULT NULL,
  REASON				varchar(500) DEFAULT NULL,
  MAKER_CHECKER_REQ		varchar(200) DEFAULT NULL,
  ENTITY_ID				int(20) DEFAULT NULL,
  CREATED_DATE			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_DATE			timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  CREATED_BY			varchar(50) DEFAULT NULL,
  UPDATED_BY			varchar(50) DEFAULT NULL,
  PRIMARY KEY (USER_ROLE_ID)
);
--------------------------------------------------------
--  DDL for Table ADMIN_USER
--------------------------------------------------------
CREATE TABLE ADMIN_USER (
  ADMIN_USER_ID			int(20) NOT NULL AUTO_INCREMENT,
  EMAIL					varchar(100) NOT NULL,
  USER_NAME				varchar(50) NOT NULL,
  FIRST_NAME			varchar(50) DEFAULT NULL,
  LAST_NAME				varchar(50) DEFAULT NULL,
  PASSWORD				varchar(200) NOT NULL,
  EMAIL_TOKEN			varchar(255) DEFAULT '',
  EMAIL_VERIFIED		int(20) DEFAULT '0',
  LANGUAGE				varchar(10) DEFAULT '',
  ADDRESS1				varchar(500) DEFAULT '',
  ADDRESS2				varchar(500) DEFAULT '',
  CITY					varchar(50) DEFAULT '',
  STATE					varchar(50) DEFAULT '',
  COUNTRY				varchar(50) DEFAULT '',
  ZIP					int(20) DEFAULT NULL,
  PHONE					varchar(20) DEFAULT NULL,
  LAST_LOGIN_IP			varchar(50) DEFAULT '',
  PREVIOUS_PASSWORDS	varchar(1000) DEFAULT NULL,
  PASS_RETRY_COUNT		int(20) DEFAULT '0',
  STATUS				varchar(50) DEFAULT 'Active',
  USER_TYPE				varchar(20) DEFAULT NULL,
  SECURITY_QUESTION		varchar(255) DEFAULT NULL,
  SECURITY_ANSWER		varchar(255) DEFAULT NULL,
  SERVICE_TYPE			int(5) DEFAULT NULL,
  CREATED_DATE			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_DATE			timestamp ,
  LAST_PASSWORD_CHANGE	timestamp ,
  LAST_LOGIN			timestamp ,
  CREATED_BY			varchar(50) NOT NULL,
  UPDATED_BY			varchar(50) DEFAULT NULL,
  REASON				varchar(50) DEFAULT NULL,
  LOGIN_MODE			int(10) DEFAULT NULL,
  USER_ROLE_ID			int(20) DEFAULT NULL,
  PRIMARY KEY (ADMIN_USER_ID),
  KEY USER_ROLE_ID (USER_ROLE_ID),
  CONSTRAINT admin_user_ibfk_1 FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLE (USER_ROLE_ID)
);

--------------------------------------------------------
--  DDL for Table USER_ROLE_ENTITY_MAP
--------------------------------------------------------
CREATE TABLE USER_ROLE_ENTITY_MAP (
  ID 					int(20) NOT NULL AUTO_INCREMENT,
  USER_ROLE_ID 			int(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);
--------------------------------------------------------
--  DDL for Table BEACON_FEATURE
--------------------------------------------------------
CREATE TABLE BEACON_FEATURE(
  FEATURE_ID			int(20) NOT NULL,
  NAME					varchar(50) DEFAULT NULL,
  FEATURE_LEVEL			int(2) DEFAULT NULL,
  ROLE_TYPE				varchar(50) DEFAULT NULL,
  REF_FEATURE_ID		int(20) DEFAULT NULL,
  STATUS				varchar(50) DEFAULT NULL,
  CREATED_DATE			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (FEATURE_ID)
);
--------------------------------------------------------
--  DDL for Table LOGIN_SESSION_DETAILS
--------------------------------------------------------
CREATE TABLE LOGIN_SESSION_DETAILS (
  ID					int(20) NOT NULL,
  SESSION_ID			varchar(255) DEFAULT NULL,
  USER_ID				int(20) NOT NULL,
  USER_NAME				varchar(50) DEFAULT NULL,
  LOGIN_STATUS			varchar(15) NOT NULL,
  LOGIN_TIME			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LOGOUT_TIME			timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  LAST_ACTIVITY_TIME	timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PORTAL_TYPE			varchar(50) DEFAULT NULL,
  IP_ADDRESS			varchar(255) DEFAULT NULL,
  BROWSER_TYPE			varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
);
--------------------------------------------------------
--  DDL for Table  PORTAL_ROLE_FEATURE_MAP
--------------------------------------------------------
CREATE TABLE PORTAL_ROLE_FEATURE_MAP (
  ROLE_FEATURE_MAP_ID	int(20) NOT NULL AUTO_INCREMENT,
  USER_ROLE_ID			int(20) DEFAULT NULL,
  FEATURE_ID			int(20) DEFAULT NULL,
  CREATED_DATE			timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_DATE			timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  CREATED_BY			varchar(50) NOT NULL,
  UPDATED_BY			varchar(50) DEFAULT NULL,
  PRIMARY KEY (ROLE_FEATURE_MAP_ID)
);
--------------------------------------------------------
--  DDL for Table ENTITY
--------------------------------------------------------   
CREATE TABLE ENTITY (
  ID 					int(20) NOT NULL,
  NAME					varchar(20) NOT NULL,
  DESCRIPTION			varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID)
);

------------------------------------------------------------------

--  DDL for Table ENTITY_FEATURE
--------------------------------------------------------
CREATE TABLE ENTITY_FEATURE (
  ID			int(20) NOT NULL,
  ENTITY_ID 	int(20) DEFAULT NULL,
  FEATURE_ID 	int(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);
  
--------------------------------------------------------
--  DDL for Table GCM_NOTIFICATION
--------------------------------------------------------

 CREATE TABLE GCM_NOTIFICATION (
  ID						int(20) NOT NULL AUTO_INCREMENT,
  USER_ID					int(20) DEFAULT NULL,
  DEVICE_REGISTRATION_ID	varchar(200) DEFAULT NULL,
  CREATED_BY				varchar(100) DEFAULT NULL,
  CREATED_DATE				timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED_BY				varchar(100) DEFAULT NULL,
  UPDATED_DATE				timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
);
---------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------
CREATE TABLE COUNTRY (
  ID		int(19) NOT NULL,
  NAME 		varchar(255) NOT NULL,
  PRIMARY KEY (ID)
);
--------   --------------------------------------------------------
--  DDL for Table STATE
--------------------------------------------------------
CREATE TABLE STATE (
  ID			int(20) NOT NULL,
  NAME			varchar(255) NOT NULL,
  STATUS		varchar(255) DEFAULT NULL,
  COUNTRY_ID	int(19) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY COUNTRY_ID(COUNTRY_ID),
  CONSTRAINT state_ibfk_1 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
);

-------------------------------------------------------------------------
--  DDL for Table REGISTRATION
------------------------------------------------------------------------




CREATE TABLE REGISTRATION
(
	ID						INT(20) PRIMARY KEY AUTO_INCREMENT,
	REG_DATE				VARCHAR(50),
	VILLAGE_ID				VARCHAR(20),
	UID						VARCHAR(20),
	VILLAGE_NAME			VARCHAR(50),
	PHC						VARCHAR(50),
	ASHA_NAME				VARCHAR(50),
	ANM_NAME				VARCHAR(50),
	ASHA_FACI_NAME			VARCHAR(50),
	WOMEN_FIRST_NAME		VARCHAR(50),
	WOMEN_HUS_NAME			VARCHAR(50),
	WOMEN_SUR_NAME			VARCHAR(50),
	HUS_FIRST_NAME			VARCHAR(50),
	HUS_FATHER_NAME			VARCHAR(50),
	HUS_SUR_NAME			VARCHAR(50),
	STREET_MARITAL			VARCHAR(50),
	LANDMARK_MARITAL		VARCHAR(50),
	VILLAGE_MARITAL			VARCHAR(50),
	TALUK_MARITAL			VARCHAR(50),
	DISTRICT_MARITAL		VARCHAR(50),
	PHONE1_MARITAL			VARCHAR(50),
	PHONE2_MARITAL			VARCHAR(50),
	STREET_NATAL			VARCHAR(50),
	LANDMARK_NATAL			VARCHAR(50),
	VILLAGE_NATAL			VARCHAR(50),
	TALUK_NATAL				VARCHAR(50),
	DISTRICT_NATAL			VARCHAR(50),
	PHONE1_NATAL			VARCHAR(50),
	PHONE2_NATAL			VARCHAR(50),
	CURRENT_PLACE			VARCHAR(50),
	OTHER_CUR_PLACE			VARCHAR(50),
	AGE						INT(5),
	EDUCATION				VARCHAR(50),
	EDUCATION_OTHER			VARCHAR(50),
	RELIGION				VARCHAR(50),
	OTHER_RELIGION			VARCHAR(50),
	CASTE					VARCHAR(50),	
	CAST_CATEGORY			VARCHAR(50),
	DIABETES				VARCHAR(50),
	HYPERTENSION			VARCHAR(50),
	HEART_DISEASE			VARCHAR(50),
	JAUNDICE				VARCHAR(50),
	ANAEMIA					VARCHAR(50),
	THYROID_PROBLEM			VARCHAR(50),
	OTHER_PROBLEM			VARCHAR(50),
	PROBLEM_DESC			VARCHAR(50),
	PREGNANCY_COUNT			VARCHAR(50),
	NO_OF_CHILDREN			VARCHAR(50),
	RECENT_DELIVERY			VARCHAR(50),
	EARLY_DELIVERY			VARCHAR(50),
	CAESAREAN				VARCHAR(50),
	BREATHLESSNESS			VARCHAR(50),	
	SEVERE_PALLOR			VARCHAR(50),
	BLEED_EXCESSIVELY		VARCHAR(50),
	LMP						VARCHAR(50),	
	HEIGHT					VARCHAR(20),
	BLOOD_GROUP				VARCHAR(20),
	CREATED_DATE			VARCHAR(50),
	CREATED_BY				VARCHAR(20),
	UPDATED_DATE			VARCHAR(50),
	UPDATED_BY				VARCHAR(20)
);

-------------------------------------------------------------------------
--  DDL for Table PREGNANCY_VISIT
------------------------------------------------------------------------

CREATE TABLE PREGNANCY_VISIT
(
	ID						INT(50) PRIMARY KEY AUTO_INCREMENT,
	WOMAN_NAME				VARCHAR(50),
	VISIT_DATE				VARCHAR(50),
	WID						INT(20),
	HAVE_FEVER				VARCHAR(50),
	ISFEVER_ASSOCATED		VARCHAR(50),
	ISFEVER_COMEANDGO		VARCHAR(50),
	IS_FEEL_TIRED			VARCHAR(50),
	IS_FITS					VARCHAR(50),
	IS_CONSCIOUSNESS		VARCHAR(50),
	FELT_GIDDY				VARCHAR(50),
	HAVE_HEADACHES			VARCHAR(50),
	BLURRED_VISION			VARCHAR(50),
	IS_BREATHLESS			VARCHAR(50),
	WHEN_BREATHLESS			VARCHAR(50),
	HAVE_COUGH				VARCHAR(50),
	HOWLONG_HAVECOUGH		VARCHAR(50),
	IS_ABDOMINAL_PAIN		VARCHAR(50),
	WHERE_PAIN				VARCHAR(50),
	BABY_MOVE				VARCHAR(50),
	IS_VAGINAL_DIS			VARCHAR(50),
	IS_BLEEDING				VARCHAR(50),
	KINDOF_BLEEDING			VARCHAR(50),
	IS_WATER_BROKEN			VARCHAR(50),
	IS_BURNING_PAIN			VARCHAR(50),
	TOE_RINGS_TIGHTER		VARCHAR(50),
	IS_BANGLES				VARCHAR(50),
	IS_OUT_OFBREATH			VARCHAR(50),
	IS_TALKING				VARCHAR(50),
	UPPER_EYE_COLOR			VARCHAR(50),
	LOWER_EYE_COLOR			VARCHAR(50),
	IS_ANKLE_DEPRESS		VARCHAR(50),
	IS_EYE_SWELLING			VARCHAR(50),
	WEIGHT					VARCHAR(50),
	FIRST_WEIGHT			VARCHAR(50),
	SEC_WEIGHT				VARCHAR(50),
	THIRD_WEIGHT			VARCHAR(50),	
	FOURTH_WEIGHT			VARCHAR(50),
	WEIGHT_DATE_ONE			VARCHAR(50),
	WEIGHT_DATE_SEC			VARCHAR(50),
	WEIGHT_DATE_THIRD		VARCHAR(50),
	WEIGHT_DATE_FOUR		VARCHAR(50),
	BP						VARCHAR(50),
	FIRST_BP				VARCHAR(50),
	SEC_BP					VARCHAR(50),
	THIRD_BP				VARCHAR(50),
	FOUR_BP					VARCHAR(50),
	BP_DATE_ONE				VARCHAR(50),
	BP_DATE_SEC				VARCHAR(50),
	BP_DATE_THIRD			VARCHAR(50),
	BP_DATE_FOUR			VARCHAR(50),
	HB						VARCHAR(50),	
	FIRST_HB				VARCHAR(50),
	SEC_HB					VARCHAR(50),
	THIRD_HB				VARCHAR(50),
	FOUR_HB					VARCHAR(50),
	HB_DATE_ONE				VARCHAR(50),
	HB_DATE_SEC				VARCHAR(50),
	HB_DATE_THIRD			VARCHAR(50),
	HB_DATE_FOUR			VARCHAR(50),
	URINE					VARCHAR(50),
	FIRST_URINE				VARCHAR(50),
	SEC_URINE				VARCHAR(50),
	URINE_DATE_ONE			VARCHAR(50),
	URINE_DATE_SEC			VARCHAR(50),
	ULTRASOUND				VARCHAR(50),
	FIRST_ULTRASOUND		VARCHAR(50),
	SEC_ULTRASOUND			VARCHAR(50),
	ULTRASOUND_DATE_ONE		VARCHAR(50),
	ULTRASOUND_DATE_SEC		VARCHAR(50),
	RBS						VARCHAR(50),
	FIRST_RBS				VARCHAR(50),
	SEC_RBS					VARCHAR(50),
	RBS_DATE_ONE			VARCHAR(50),
	RBS_DATE_SEC			VARCHAR(50),
	MALARIA					VARCHAR(50),
	FIRST_MALARIA			VARCHAR(50),
	SEC_MALARIA				VARCHAR(50),
	MALARIA_DATE_ONE		VARCHAR(50),
	MALARIA_DATE_SEC		VARCHAR(50),
	SPUTUM					VARCHAR(50),
	SPUTUM_TEST				VARCHAR(50),
	SPUTUM_DATE				VARCHAR(50),
	TALKING_IRRELEVANTLY	VARCHAR(50),
	CREATED_DATE			VARCHAR(50),
	CREATED_BY				VARCHAR(50),
	UPDATED_DATE			VARCHAR(50),
	UPDATED_BY				VARCHAR(50)
);

ALTER TABLE PREGNANCY_VISIT ADD FOREIGN KEY (WID) REFERENCES REGISTRATION(UID);


-------------------------------------------------------------------------
--  DDL for Table POSTPARTUM_VISIT
------------------------------------------------------------------------

CREATE TABLE POSTPARTUM_VISIT
(
	ID						INT(50) PRIMARY KEY AUTO_INCREMENT,
	WOMAN_NAME				VARCHAR(50),
	VISIT_DATE				VARCHAR(50),
	WID						INT(20),
	HAVE_FEVER				VARCHAR(50),
	ISFEVER_ASSOCATED		VARCHAR(50),
	ISFEVER_COMEANDGO		VARCHAR(50),
	IS_FEEL_TIRED			VARCHAR(50),
	IS_FITS					VARCHAR(50),
	IS_CONSCIOUSNESS		VARCHAR(50),
	FELT_GIDDY				VARCHAR(50),
	HAVE_HEADACHES			VARCHAR(50),
	BLURRED_VISION			VARCHAR(50),
	ISDIFFICULT_FEED		VARCHAR(50),
	PAIN_IN_BREAST			VARCHAR(50),
	LUMP_IN_BREAST			VARCHAR(50),
	IS_BREATHLESS			VARCHAR(50),
	WHEN_BREATHLESS			VARCHAR(50),
	HAVE_COUGH				VARCHAR(50),
	HOWLONG_HAVECOUGH		VARCHAR(50),
	IS_ABDOMINAL_PAIN		VARCHAR(50),
	WHERE_PAIN				VARCHAR(50),
	BABY_MOVE				VARCHAR(50),
	IS_VAGINAL_DIS			VARCHAR(50),
	IS_BLEEDING				VARCHAR(50),
	NO_DAY_AFTER_DEL		VARCHAR(50),
	NO_OF_CLOTHES			VARCHAR(50),
	ISPASSCLOT_BLEEDING		VARCHAR(50),
	HAS_BLEEDING_INCREASE	VARCHAR(50),
	IS_BURNING_PAIN			VARCHAR(50),
	IS_OUT_OFBREATH			VARCHAR(50),
	IS_TALKING				VARCHAR(50),
	UPPER_EYE_COLOR			VARCHAR(50),
	LOWER_EYE_COLOR			VARCHAR(50),
	IS_ANKLE_DEPRESS		VARCHAR(50),
	IS_EYE_SWELLING			VARCHAR(50),
	BP						VARCHAR(50),
	FIRST_BP				VARCHAR(50),
	SEC_BP					VARCHAR(50),
	BP_DATE_ONE				VARCHAR(50),
	BP_DATE_SEC				VARCHAR(50),
	HB						VARCHAR(50),	
	FIRST_HB				VARCHAR(50),
	SEC_HB					VARCHAR(50),
	HB_DATE_ONE				VARCHAR(50),
	HB_DATE_SEC				VARCHAR(50),
	URINE					VARCHAR(50),
	FIRST_URINE				VARCHAR(50),
	SEC_URINE				VARCHAR(50),
	URINE_DATE_ONE			VARCHAR(50),
	URINE_DATE_SEC			VARCHAR(50),
	MALARIA					VARCHAR(50),
	FIRST_MALARIA			VARCHAR(50),
	SEC_MALARIA				VARCHAR(50),
	MALARIA_DATE_ONE		VARCHAR(50),
	MALARIA_DATE_SEC		VARCHAR(50),
	SPUTUM					VARCHAR(50),
	SPUTUM_TEST				VARCHAR(50),
	SPUTUM_DATE				VARCHAR(50),
	TALKING_IRRELEVANTLY	VARCHAR(50),
	ISHEARING_IMAGINARY		VARCHAR(50),
	CARRING_BABYANDHERSELF	VARCHAR(50),
	CREATED_DATE			VARCHAR(50),
	CREATED_BY				VARCHAR(50),
	UPDATED_DATE			VARCHAR(50),
	UPDATED_BY				VARCHAR(50)
);

ALTER TABLE POSTPARTUM_VISIT ADD FOREIGN KEY (WID) REFERENCES REGISTRATION(UID);

-------------------------------------------------------------------------
--  DDL for Table DELIVERY
------------------------------------------------------------------------

CREATE TABLE DELIVERY
(
	ID						INT(50) PRIMARY KEY AUTO_INCREMENT,
	WOMAN_NAME				VARCHAR(50),
	VISIT_DATE				VARCHAR(50),
	WID						INT(20),
	DELIVERY_DATE			VARCHAR(50),
	PREGNANCY_LAST			VARCHAR(50),
	IS_BABY_ALIVE			VARCHAR(50),
	DELIVERY_PLACE			VARCHAR(50),
	OTHER_PLACE				VARCHAR(50),
	DELIVERY_CONDUCTEDBY	VARCHAR(500),
	DELIVERY_TYPE			VARCHAR(50),
	BABY_WEIGHT				VARCHAR(50),
	ISEXCE_BLEEDING			VARCHAR(50)
);
ALTER TABLE DELIVERY ADD FOREIGN KEY (WID) REFERENCES REGISTRATION(UID);

-------------------------------------------------------------------------
--  DDL for Table SYMPTOM
------------------------------------------------------------------------

CREATE TABLE SYMPTOM 
(
	ID						INT(50) PRIMARY KEY AUTO_INCREMENT,
	SYMPTOM_ID				VARCHAR(50),
	SYMPTOM_PHRASES			VARCHAR(500)	
);
